name: InventoryWeight
version: 2.1
author: wonka19
main: me.wonka01.InventoryWeight.InventoryWeight
api-version: 1.13

softdepend: [PlaceholderAPI]

commands:
  inventoryweight:
    aliases: iw
    description: Commands for Inventory Weight Plugin
    usage: /iw [help, weight, get, level, preview, tempforce] are the available commands

permissions:
  inventoryweight.reload:
    description: Can use the reload command to update the configuration file
    default: op
  inventoryweight.off:
    description: If this is set a player will not have their weight monitored or their speed changed
    default: false
  inventoryweight.level.set:
    description: Set a player's inventory weight level
    default: op
  inventoryweight.level.add:
    description: Add to a player's inventory weight level
    default: op
  inventoryweight.preview:
    description: Preview level multipliers and max weight from config
    default: op
  inventoryweight.tempforce:
    description: Temporarily force enable/disable weight for a player ignoring world list
    default: op
